[package]
name = "playlist"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.12", features = [
    "blocking",
    "json",
] } # For API calls
serde_json = "1.0"
